version: '3'
services:
  golang:
    image: "amqtt"
    container_name: amqtt
    build: ./amqtt
    restart: always
    ports:
      - "1884:1884"
      - "8086:8086"
      - "2884:2884"
    environment:
      - CONFIG=/go/amqtt.toml
    volumes:
      - ./conf.toml:/go/amqtt.toml
    networks:
      - default
networks:
  default:
    external:
      name: aimore