tcpHost = "0.0.0.0"
tcpPort = 1884
tcpTls = true

ca = "certs/root.crt"
certFile = "certs/server.crt"
keyFile = "certs/server.key"

clientCertFile = "certs/client.crt"
clientKeyFile = "certs/client.key"

websocket = true
wsHost = "0.0.0.0"
wsPort = 8086
wsTls = true
wsPath = "/mqtt"

isCluster = true
clusterName = "node1"
clusterHost = "0.0.0.0"
clusterPort = 2884
clusterTls = true

[[clusters]]
name = "node2"
host = "localhost:2885"