tcpHost = "0.0.0.0"
tcpPort = 1884
tcpTsl = false

wsHost = "0.0.0.0"
wsPort = 8085
wsTsl = false

caFile = "cafile"
ceKey = "cefile"

clusterName = "node1"
clusterHost = "0.0.0.0"
clusterPort = 1882
clusterTsl = false

[[clusters]]
name = "node2"
host = "127.0.0.1"
port = 8882
tsl = false