tcpHost = "0.0.0.0"
tcpPort = 1884
tcpTsl = true

wsHost = "0.0.0.0"
wsPort = 8085
wsTsl = false
wsPath = "mqtt"

caFile = "certs/server.crt"
ceKey = "certs/server.key"

isCluster = false
clusterName = "node1"
clusterHost = "0.0.0.0"
clusterPort = 1882
clusterTsl = false

[[clusters]]
name = "node2"
host = "127.0.0.1:8882"