tcpHost = "0.0.0.0"
tcpPort = 1884
tcpTsl = true

websocket = true
wsHost = "0.0.0.0"
wsPort = 8086
wsTsl = false
wsPath = "mqtt"

caFile = "certs/server.crt"
ceKey = "certs/server.key"

isCluster = true
clusterName = "node1"
clusterHost = "0.0.0.0"
clusterPort = 2884
clusterTsl = false

[[clusters]]
name = "node2"
host = "127.0.0.1:8882"