tcpHost = "0.0.0.0"
tcpPort = 1885
tcpTls = true

ca = "certs/root.crt"
certFile = "certs/server.crt"
keyFile = "certs/server.key"

clientCertFile = "certs/client.crt"
clientKeyFile = "certs/client.key"

websocket = false
wsHost = "0.0.0.0"
wsPort = 8087
wsTls = false
wsPath = "/mqtt"

isCluster = true
clusterName = "node2"
clusterHost = "0.0.0.0"
clusterPort = 2885
clusterTls = true

[[clusters]]
name = "node1"
host = "localhost:2884"